spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8008

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
